### ISSUE TITLE
Cache all contexts in uni-tests & bdd-tests

### ISSUE THREAD

**Issue by sudeshrshetty** [hyperledger/aries-framework-go#1846]
to avoid errors like these in CIs

```
--- FAIL: TestVerifyProof (0.49s)
panic: failed to normalize JSON-LD document: loading remote context failed: Dereferencing a URL did not result in a valid JSON-LD context: https://www.w3.org/ns/did/v1 [recovered]
	panic: failed to normalize JSON-LD document: loading remote context failed: Dereferencing a URL did not result in a valid JSON-LD context: https://www.w3.org/ns/did/v1

goroutine 59 [running]:
testing.tRunner.func1.1(0xbde4e0, 0xc00041e080)
	/opt/hostedtoolcache/go/1.14.3/x64/src/testing/testing.go:940 +0x421
testing.tRunner.func1(0xc000233c20)
	/opt/hostedtoolcache/go/1.14.3/x64/src/testing/testing.go:943 +0x600
panic(0xbde4e0, 0xc00041e080)
	/opt/hostedtoolcache/go/1.14.3/x64/src/runtime/panic.go:975 +0x3e3
github.com/hyperledger/aries-framework-go/pkg/doc/did.createSignedDidDocument(0xc00043ab80, 0x40, 0x40, 0xc0000fc680, 0x20, 0x20, 0x40, 0x40, 0x0)
	/home/runner/work/aries-framework-go/aries-framework-go/pkg/doc/did/doc_test.go:1434 +0x373
github.com/hyperledger/aries-framework-go/pkg/doc/did.TestVerifyProof(0xc000233c20)
	/home/runner/work/aries-framework-go/aries-framework-go/pkg/doc/did/doc_test.go:955 +0x15e
```

**Comment by kdimak** [comment]
TODO: add an option for definition of custom JSONLD loader for DID doc verification.
