### ISSUE TITLE
panic: cannot parse did document with `@base`

### ISSUE THREAD

**Issue by llorllale** [hyperledger/aries-framework-go#2133]
<details><summary>Test Case</summary>

```go
func TestBaseContext(t *testing.T) {
	test := `{
    "@context": [
        "https://www.w3.org/ns/did/v1",
        {
            "@base": "did:sidetree:EiBFsUlzmZ3zJtSFeQKwJNtngjmB51ehMWWDuptf9b4Bag"
        }
    ],
    "authentication": [
        "#signingKey"
    ],
    "id": "did:sidetree:EiBFsUlzmZ3zJtSFeQKwJNtngjmB51ehMWWDuptf9b4Bag",
    "publicKey": [
        {
            "controller": "",
            "id": "#signingKey",
            "publicKeyJwk": {
                "crv": "secp256k1",
                "kty": "EC",
                "x": "y9kzrVBqXx24sVMEQQk4Ce-0bqZ1i5TwxllWCkzA7wU",
                "y": "c2JHxQqUUtyWILAIicmpBGC47PgmJT465tPocG2q18k"
            },
            "type": "EcdsaSecp256k1VerificationKey2019"
        }
    ],
    "service": [
        {
            "id": "#serviceEndpointId123",
            "serviceEndpoint": "https://www.url.com",
            "type": "someType"
        }
    ]
}`
	_, err := ParseDocument([]byte(test))
	require.NoError(t, err)
}
```

</details>

<details><summary>Stacktrace</summary>

```
panic: interface conversion: interface {} is map[string]interface {}, not string [recovered]
	panic: interface conversion: interface {} is map[string]interface {}, not string

goroutine 19 [running]:
testing.tRunner.func1.1(0x932380, 0xc00024ca80)
	/usr/local/go/src/testing/testing.go:940 +0x2f5
testing.tRunner.func1(0xc00014d560)
	/usr/local/go/src/testing/testing.go:943 +0x3f9
panic(0x932380, 0xc00024ca80)
	/usr/local/go/src/runtime/panic.go:969 +0x166
github.com/hyperledger/aries-framework-go/pkg/doc/did.(*rawDoc).ParseContext(0xc000264000, 0x0, 0x0, 0xc00013afd0)
	/home/llorllale/dev/hyperledger/aries-framework-go/pkg/doc/did/doc.go:600 +0x2fe
github.com/hyperledger/aries-framework-go/pkg/doc/did.(*rawDoc).schemaLoader(0xc000264000, 0x36e, 0x380)
	/home/llorllale/dev/hyperledger/aries-framework-go/pkg/doc/did/doc.go:614 +0x2f
github.com/hyperledger/aries-framework-go/pkg/doc/did.ParseDocument(0xc000168a80, 0x36e, 0x380, 0xc000168a80, 0x36e, 0x380)
	/home/llorllale/dev/hyperledger/aries-framework-go/pkg/doc/did/doc.go:261 +0x15f
github.com/hyperledger/aries-framework-go/pkg/doc/did.TestBaseContext(0xc00014d560)
	/home/llorllale/dev/hyperledger/aries-framework-go/pkg/doc/did/doc_test.go:1453 +0x65
testing.tRunner(0xc00014d560, 0xb0b670)
	/usr/local/go/src/testing/testing.go:991 +0xdc
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1042 +0x357
```

</details>

**Comment by llorllale** [comment]
Relevant part of the sidetree spec:

> If the DID Document is being rendered in the JSON-LD representation variant, the implementer SHOULD add an @base entry to the document’s @context, and set the @base value to the id of the resolved DID. This ensures relative path values in the output DID Document are correctly projected into id-related strings by JSON-LD parsers.

Relevant part of the [did-core spec](https://www.w3.org/TR/did-core/#production-0):

> The value of the @context property MUST be one or more URIs, where the value of the first URI is https://www.w3.org/ns/did/v1. All members of the @context property MUST exist be in the DID properties extension registry. 

The sidetree spec seems to be conflicting with did-core.

**Comment by llorllale** [comment]
decentralized-identity/sidetree#842

Sidetree may end up using relative URLs as [described in did-core](https://w3c.github.io/did-core/#relative-did-urls).

**Comment by llorllale** [comment]
Blocked by decentralized-identity/sidetree#842
