### ISSUE TITLE
Cannot register a new message service on mobile

### ISSUE THREAD

**Issue by adn-misa** [hyperledger/aries-framework-go#3083]
**What I'm trying to do**

I'm trying to register a new message service on mobile.

**Expected result**

It should successfully register the new message service.
The same call over REST is working correctly.

**Actual result**

The library crashes due to a null pointer reference after executing the following code:

```kotlin
val messagingController = ariesAgent.messagingController
val res = messagingController.registerService(RequestEnvelope("{\"name\":\"basic-message\", \"purpose\":[\"chat\"], \"type\":\"https://didcomm.org/basicmessage/2.0\"}".toByteArray(Charsets.UTF_8)))
```

Stacktrace:

```
E/Go: panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x7310a15e20]
    goroutine 17 [running, locked to thread]:
    github.com/hyperledger/aries-framework-go/pkg/client/messaging.(*Client).RegisterService(0x4000034180, 0x4000504130, 0xd, 0x40000bc120, 0x2c, 0x40003ee140, 0x1, 0x4, 0x4000422b50, 0x400037ac00)
    	aries-framework-go/pkg/client/messaging/client.go:143 +0xd0
    github.com/hyperledger/aries-framework-go/pkg/controller/command/messaging.(*Command).registerMessageService(0x4000010030, 0x40003ee100, 0x40003ee100, 0x0)
E/Go: 	aries-framework-go/pkg/controller/command/messaging/command.go:283 +0x290
    github.com/hyperledger/aries-framework-go/pkg/controller/command/messaging.(*Command).RegisterService(0x4000010030, 0x7310d1e308, 0x40003ec120, 0x7310d1e328, 0x40003ec150, 0x7310c7c4a0, 0x400029c001)
    	aries-framework-go/pkg/controller/command/messaging/command.go:125 +0x2ac
    github.com/hyperledger/aries-framework-go/cmd/aries-agent-mobile/pkg/wrappers/command.exec(0x40000322d0, 0x7310c7f920, 0x40003ee0c0, 0x40003ee0c0, 0x40002983d0, 0x0, 0x0)
    	aries-framework-go/cmd/aries-agent-mobile/pkg/wrappers/command/command.go:27 +0x188
    github.com/hyperledger/aries-framework-go/cmd/aries-agent-mobile/pkg/wrappers/command.(*Messaging).RegisterService(0x40000c4040, 0x40003f20c0, 0x40003f20c0)
    	aries-framework-go/cmd/aries-agent-mobile/pkg/wrappers/command/messaging.go:30 +0x188
    main.proxyapi_MessagingController_RegisterService(0xffffffe2ffffffe3, 0x73104b0001)
    	gomobile-work-567519127/src/gobind/go_apimain.go:2410 +0x7c
A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 24848 (DefaultDispatch)
```

The error seems to come from a missing notifier that the messaging client should have (aries-framework-go/pkg/client/messaging/client.go:143).
I tried to check if `registerHandler(topic: String, message: ByteArray)` could solve the problem but I could not figure it out.

**Comment by adn-misa** [comment]
After some analysis, I found the culprit.

In file `aries-framework-go/cmd/aries-agent-mobile/pkg/wrappers/command/aries.go` [line 72](https://github.com/hyperledger/aries-framework-go/blob/34ff560ed041fd9d3255a0c8c7f99c584c1c0a74/cmd/aries-agent-mobile/pkg/wrappers/command/aries.go#L72), there is a message handler that was forgotten to be passed as parameter to the function `GetCommandHandlers`.

The inspiration to the solution can be checked on the implementation of the REST service in file `aries-framework-go/cmd/aries-agent-rest/startcmd/start.go` [line 634](https://github.com/hyperledger/aries-framework-go/blob/34ff560ed041fd9d3255a0c8c7f99c584c1c0a74/cmd/aries-agent-rest/startcmd/start.go#L634).

If I find time, I will try to make a pull request next week.

**Comment by adn-misa** [comment]
Created a pull request #3086

**Comment by adn-misa** [comment]
Pull request was merged
