### ISSUE TITLE
`make bdd-test` fails

### ISSUE THREAD

**Issue by llorllale** [hyperledger/aries-framework-go#517]
`make bdd-test` fails on my system:

```
llorllale@dominica:~/dev/hyperledger/aries-framework-go$ make bdd-test 
rm -f coverage.txt
rm -Rf ./build
rm -Rf ./test/bdd/db
rm -Rf ./test/bdd/fixtures/keys/tls
rm -Rf ./test/bdd/*.log
Generating Aries-Framework-Go Test PKI
Signature ok
subject=/C=CA/ST=ON/O=Example Inc.:Aries-Framework-Go/OU=Aries-Framework-Go/CN=*.example.com
Getting CA Private Key
done generating Aries-Framework-Go PKI
Running aries-framework-go integration tests...
panic: Error composing system in BDD context: Error creating new composition 'ee49919f187e41f4aa2dca5940464471' using compose yaml 'docker-compose.yml':  Error issuing command to docker-compose with args '[up --force-recreate -d]':  exec: "docker-compose": executable file not found in $PATH ()

goroutine 1 [running]:
github.com/hyperledger/aries-framework-go/test.TestMain.func1.1()
        /home/llorllale/dev/hyperledger/aries-framework-go/test/bdd/bddtests_test.go:49 +0x402
github.com/DATA-DOG/godog.(*Suite).run(0xc00033fd40)
        /home/llorllale/go/pkg/mod/github.com/!d!a!t!a-!d!o!g/godog@v0.7.13/suite.go:216 +0x4d
github.com/DATA-DOG/godog.(*runner).run(0xc000171740, 0x14)
        /home/llorllale/go/pkg/mod/github.com/!d!a!t!a-!d!o!g/godog@v0.7.13/run.go:76 +0xae
github.com/DATA-DOG/godog.RunWithOptions(0xc9be66, 0x6, 0xcd3800, 0x0, 0x15cebd8d92b97135, 0x101, 0xc99eff, 0x3, 0xc9dbf6, 0x8, ...)
        /home/llorllale/go/pkg/mod/github.com/!d!a!t!a-!d!o!g/godog@v0.7.13/run.go:173 +0x8d8
github.com/hyperledger/aries-framework-go/test.TestMain(0xc0001d9d80)
        /home/llorllale/dev/hyperledger/aries-framework-go/test/bdd/bddtests_test.go:38 +0x2df
main.main()
        _testmain.go:94 +0x1c1
FAIL    github.com/hyperledger/aries-framework-go/test  0.022s
FAIL
Makefile:32: recipe for target 'bdd-test' failed
make: *** [bdd-test] Error 1
```

**Comment by llorllale** [comment]
Right, this was due to not having `docker-compose` in my system.
